baseurl = "https://harishguda.me"
languageCode = "en-us"
title = "Harish Guda"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"


[[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/files/cv-harishguda.pdf"
    weight = 4
[[menu.main]]
    name = "Miscellany"
    url = ""
    weight = 5
[[menu.main]]
    name = "Charity"
    url = "/charity"
    weight = 6

[params]
    description = "Personal Webpage"
    footer = "&copy; [Harish Guda](https://harishguda.me/about)"
