---
title: "Discovering My Joy of Running and Racing"
author: "Harish Guda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In the last few months, I took up running more actively, as I continue this journey of wanting to be more fit and healthy. I had written about my first race --- ASU's very own Pat Tillman Race --- in an other [post](https://harishguda.me/post/2023/04/15/run/). I had such a runner's high after my first race that I wanted more of it. Is this an [addictive good](https://en.wikipedia.org/wiki/Rational_addiction)? Hmm.  

It was at this time that I started Googling what races happen around me, and the distances and speeds I should aspire to. I started signing up for 5ks in mid-April 2023, and realized quickly that 5ks wouldn't cut it anymore. I wanted a longer, and perhaps, a more involved exercise.

# The Long Phoenix Summer Lull

Then began the summer of Arizona and I stayed indoor until September. While running at Orangetheory was my main getaway, I kept signing up for races that I wanted to run once the cooler temperatures in Phoenix set in (in Fall and Winter). As my friends started to sign-up for various races, it had a complimentary effect on my decision, and I quickly realized I signed up for too many races. 

Here are the races I will be running this cycle (before Summer 2024 kicks in): 

- ASU West Homecoming (10K): Oct 22nd.
- Run for Ryan House (10K): Nov 5th.
- Lululemon Scottsdale (10K): Nov 12th. 
- Gilbert Marathon (10k): Nov 18th. 
- Phoenix Hot Chocolate (15K): Dec 17th.
- Rock n Roll AZ (Half-Marathon): Jan 14th. 
- Mesa Marathon (10K): Feb 10th. 

Besides, I will also be running the Pittsburgh half marathon on May 5th, while I visit a friend there. 

Phew! That's quite a list. 

While Strava is awesome, and I discover a lot of fun runs via Strava, I now created an Instagram account to document my race days, perhaps as a commitment device that makes me signup and run these races. My current plan is to do 10 X 10K's a year, and 3 X half-marathons a year. Fingers crossed.   

# Training Routine

The bedrock of my training is Orangetheory. I have been a long-time OTF-er (more than 500 classes now), and I do not plan to quit anytime soon. I am supplementing my OTF classes with long runs. I joined a Strava group called [DTPHX Run Club](https://www.instagram.com/dtphxrun/) on their Thursday runs near the Tempe Town Lake for their long runs (about 9-11K). 

The group also meets at other parts of Phoenix on other days, but I am quite time-constrained this semester.^[This is my teaching semester, and I have a lot of research work to complete this semester. Reviewing papers is also taking up a significant amount of my time.] I have been struggling with a weird hip-flexor strain that prevents me from doing too many runs in a week. 

# Resources and Gear

While popular wisdom is that running is cheap, I found that a pain-free and a happy running experience is not. I had to invest a reasonable amount of money in buying the right gear: clothes, shoes, socks, water bottle, undies, sunglasses, etc. I will write a longer post on running gear, and cross-fit/OTF gear.

Besides, race signups also involves a significant amount of money. 

# Completed Races Thus Far

Here are the races I have finished thus far. 

## [ASU West Homecoming Sparky Challenge](https://asuevents.asu.edu/event/sparkys-challenge-2023?eventDate=2023-10-22)

This was my first time visiting ASU's sister campus in Glendale. This city has been in the news a lot, due to TSMC's new campus, and the growing economic activity in this area. However, I was not super impressed with this city during my short visit -- it just feels like suburban doom sprawl. Just, endless streets of cookie-cutter single family homes. I was impressed with the ASU West campus though. It has a close-knit, small campus feel (unlike Tempe's mega campus). 

The run itself was not too great. The run was organized at 3pm on a late October Sunday, where the temperature was about 39C. I hated most of the run, and had to take walking breaks every 15 minutes. My timing in this race was about 11:33 minutes/mile, arguably my worst timing due to the severe heat. 

<center>

<div class="strava-embed-placeholder" data-embed-type="activity" data-embed-id="10087556434"></div><script src="https://strava-embeds.com/embed.js"></script>

</center>

## [Run for Ryan House](https://ryanhouse.org/run-ryan-house-3/)

Ryan House is a wonderful charity that supports families facing pediatric end-of-life situations. They also provide bereavement support for families before and after the death of a child. I support this organization through my run every year. 

The race is organized in Mesa's riverview park (next to the Spring training facility). It is a beautiful part of the town and I enjoy it quite a lot. The stretch over the top of the lake is quite enjoyable. 

<center>

<div class="strava-embed-placeholder" data-embed-type="activity" data-embed-id="10166011189"></div><script src="https://strava-embeds.com/embed.js"></script>

</center>

I did much better in terms of timing, about 9:58 minutes/mile. 

## [Lululemon Scottsdale 10K](https://lululemon10ktour.com/tour/10k-tour-scottsdale/)

Scottsdale is arguably the most bougie city in the US. I never enjoyed the vibe -- posh, fake, flamboyant -- that I get in this city. 

Nevertheless, the run was extremely well organized, with a lot of support from crowd. The registration was expensive (about $89), but the post race swag was great. The run starts near Old Town Scottsdale, and goes along the canal. 

<center>

<div class="strava-embed-placeholder" data-embed-type="activity" data-embed-id="10206842353"></div><script src="https://strava-embeds.com/embed.js"></script>

</center>

This was probably my best in terms of timing so far. I had gotten at 9:47 minutes/mile, and I believe I could have easily gotten a lot lower, but for the congestion (7,500 runners over a narrow strip is no joke!)

# Looking Forward

The run I am most looking forward to is the Tempe Rock n Roll Half Marathon.^[If you are interested in running this race, please let me know. I will be happy to host you!] I had walked, biked, and driven through these roads for the past five years, and I finally will race them. I will continue to train for the next two months, and will look to have fun in my first half marathon. 

