---
title: "Some Information on Creating Websites with R"
author: "Harish Guda"
date: "2019-04-18"
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
slug: "website-info"
categories: 
  - "General"
tags: 
  - "Creating Websites"
  - "R"
---

I have always wanted to build attractive websites and still have a lot of control on the various facets of the website. I had previously owned a Google Site, which I never liked I am not a professional with regards to web-development. Besides, my needs were minimal. With little knowledge on this topic, I did what everyone else does -- dive straight into it. 

I am quite comfortable with R, and when Yihui Xie and co-authors came out with the book on [blogdown](https://bookdown.org/yihui/blogdown/), I wasted no time. However, it can be still quite difficult with no experience on HTML, or prior exposure to CSS (which is me!). Some useful tutorials are from [Alison Hill](https://alison.rbind.io/post/up-and-running-with-blogdown/#in-github) (who is a co-author on the textbook) and [Chi Zhang](https://andreaczhang.rbind.io/post/my-1st-blogpost/). 

I had owned a custom domain (bought from Google Domains), and continued as the tutorials suggested. I hope it works for you if you plan to use it too. 